### ISSUE TITLE
nvm - strange error

### ISSUE THREAD

**Issue by palandovalex** [bash-lsp/bash-language-server#392]
I am using nvm, and i installed this package

But when i tried to run it in terminal - i get this stack trace:

```

Unknown command '/home/apalandov/.nvm/versions/node/v18.1.0/bin/node /home/apalandov/.npm-global/bin/bash-language-server'. Run with -h for help.
(node:1466264) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/deps/undici/undici:4816
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /home/apalandov/.npm-global/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
........
      at /home/apalandov/.npm-global/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/home/apalandov/.npm-global/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.1.0
```

**Comment by skovhus** [comment]
This should be fixed in 3.0.1, can you verify this? It was an issue with node 18 support.

**Comment by palandovalex** [comment]
in this moment i  solve it by downgrade node

**Comment by mellery451** [comment]
I have 3.0.3 installed via homebrew and still have this problem.

**Comment by skovhus** [comment]
Node 18 support should be fixed in 3.0.3.
