### ISSUE TITLE
[FEATURE] Add code action support for shellcheck

### ISSUE THREAD

**Issue by cryptomilk** [bash-lsp/bash-language-server#490]
Till now I used [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/) with shellcheck. The nice thing was that it supported code action. The code action added comments like:

```sh
# shellcheck disable=2181
```
You could select if you want it added globally or local. It would be nice to get this with bashls.

**Comment by skovhus** [comment]
Shellcheck has been supported since version 3 that was released in march (https://github.com/bash-lsp/bash-language-server/pull/342). There has been some improvements to it, recently we also find the binary if you don't provide it as a configuration option.

Let me know if it works for you.

**Comment by cryptomilk** [comment]
The shellcheck integration doesn't provide code actions ...

**Comment by skovhus** [comment]
Ah yes, I read this one too quickly. We should definitely support code actions. Let me know if you want to help out adding this.

**Comment by skovhus** [comment]
A first version supporting this has just been released as `bash-language-server@4.0.0-beta.3`, not released in the VSCode extension yet.

Can you try it out @cryptomilk and let me know what is missing compared to null-ls?

`npm install -g bash-language-server@4.0.0-beta.3`

**Comment by laodzu** [comment]
Cool!  This works out of the box in Emacs master with eglot.  With 4.0.0-beta.3 I get code actions for the notes and warnings.  But clicking on a position, I get a selection list with all the problems until the end of the buffer. Selecting the first item fixes the site I selected, but the other items fix problems "further down".

But hey, that's a big step in the right direction, thanks!

**Comment by skovhus** [comment]
> But clicking on a position, I get a selection list with all the problems until the end of the buffer. Selecting the first item fixes the site I selected, but the other items fix problems "further down".

Thanks for testing this! I'm curious to figure out where the problem lies here. Can you share a code snippet?

**Comment by laodzu** [comment]
Sure!  The script is an easy one for me to figure out which settings the gnome-settings GUI changes:

```
#!/bin/sh

BEFORE=$(mktemp /tmp/gsettingsXXXXX)
gsettings list-recursively > $BEFORE
echo -n "Ok, recorded current settings - now do the change and press enter ..."
read ANS
AFTER=`mktemp /tmp/gsettingsXXXXX`
gsettings list-recursively > $AFTER
diff -u $BEFORE $AFTER
rm $BEFORE $AFTER
```

This will complain 7 times for SC2086.  Clicking on an occurrence of $AFTER will present me a list with only this incidence to fix, but clicking on one of the occurrences of SC2006 (Use $(..) instead of ``) gives me a list of all code fixes for the buffer.  
Hm, so my previous description of the failure wasn't really accurate, sorry.  It seems that the SC2006 actions present all fixes for the buffer but the SC2086 does not.  Hm, no idea why this is the case.

**Comment by Shane-XB-Qian** [comment]
following was sent to server:

`{'method': 'textDocument/codeAction', 'params': {'context': {'diagnostics': [{'range': {'end': {'character': 35, 'line': 7}, 'start': {'character': 29, 'line': 7}}, 'source': 'shellcheck', 'code': 'SC2086', 'message': 'Double quote to prevent globbing and word splitting.', 'codeDescription': {'href': 'https://www.shellcheck.net/wiki/SC2086'}, 'severity': 3}], 'triggerKind': 1}, 'range': {'end': {'character': 35, 'line': 7}, 'start': {'character': 0, 'line': 7}}, 'textDocument': {'uri': 'file:///tmp/bashls_code_action.sh'}}}`

but got empty result `[]` from server, was there something wrong?
// though client is vim

**Comment by David-Else** [comment]
Hi, I am using `bash-language-server@4.1.3` and a binary of `ShellCheck 0.8.0` in Helix with default settings.

Can someone please give an example of some code for a code action that should work for me to test? The script in  https://github.com/bash-lsp/bash-language-server/issues/490#issuecomment-1338164173 shows plenty of errors, but when I try to run a code action on any of them I get `no code action available`:

![Screenshot from 2022-12-30 15-21-04](https://user-images.githubusercontent.com/12832280/210086114-77cd6047-778b-492f-80a9-3c5a40468f15.png)

**Comment by Shane-XB-Qian** [comment]
i think there No code action from this bash lsp server yet, for now.
// or not sure if it was much useful for bash (vs java perhaps must be) or not, IMO.

// BTW: what's editor you are using? it looks nice.. :-)

**Comment by David-Else** [comment]
@Shane-XB-Qian There should be code actions, it was added: https://github.com/bash-lsp/bash-language-server/blob/main/server/CHANGELOG.md#401

The editor is Helix, it is amazing! You are seeing the result of displaying all diagnostics, you can move between them and go straight to the result. I am using the built-in VS Code theme. Check it out, https://helix-editor.com/

**Comment by Shane-XB-Qian** [comment]
i roughly checked that check-in code, but unfortunately seems it did not actually return any `code action` piece to lsp client. 
those hint list in your left side of screen cut actually was just its diagnose list.

**Comment by David-Else** [comment]
@skovhus Could you help? I tried the following examples of errors in Helix from https://github.com/koalaman/shellcheck/blob/master/README.md#gallery-of-bad-code and non provided a code action:
```
#!/bin/bash

echo $1                           # Unquoted variables
find . -name *.ogg                # Unquoted find/grep patterns
rm "~/my file.txt"                # Quoted tilde expansion
v='--verbose="true"'; cmd $v      # Literal quotes in variables
echo 'Don't forget to restart!'   # Singlequote closed by apostrophe
echo 'Don\'t try this at home'    # Attempting to escape ' in ''
echo 'Path is $PATH'              # Variables in single quotes
trap "echo Took ${SECONDS}s" 0    # Prematurely expanded trap
unset var[i]                      # Array index treated as glob

[[ n != 0 ]]                      # Constant test expressions
[[ -e *.mpg ]]                    # Existence checks of globs
[[ $foo==0 ]]                     # Always true due to missing spaces
[[ -n "$foo " ]]                  # Always true due to literals
[[ $foo =~ "fo+" ]]               # Quoted regex in =~
[ foo =~ re ]                     # Unsupported [ ] operators
[ $1 -eq "shellcheck" ]           # Numerical comparison of strings
[ $n && $m ]                      # && in [ .. ]
[[ "$$file" == *.jpg ]]           # Comparisons that can't succeed
(( 1 -lt 2 ))                     # Using test operators in ((..))
[ x ] & [ y ] | [ z ]             # Accidental backgrounding and piping
```

**Comment by skovhus** [comment]
The code actions feature is complete, here I'm demoing bash language server through the vscode extension (see the gif below). 

I'm using the script in https://github.com/bash-lsp/bash-language-server/issues/490#issuecomment-1338164173 to show case code actions and some diagnostics that has code actions, but where the severity is low so it doesn't show up in the "problems" view (i.e. `SC2006`).

So I'll close this issue now, please open a new one if you find something that isn't working with bash-language-server. 

![code-actions](https://user-images.githubusercontent.com/1260305/211145455-41b67282-be33-4765-8d6e-78c225f14584.gif)

**Comment by Shane-XB-Qian** [comment]
@skovhus i am using same example code like you said https://github.com/bash-lsp/bash-language-server/issues/490#issuecomment-1338164173 but lsp client sent to this bashls with the content https://github.com/bash-lsp/bash-language-server/issues/490#issuecomment-1340637970 but get reply empty result, could you check what's wrong here? same code worked for java and rust, but not this (bash). not sure was a server or client issue.

**Comment by gegoune** [comment]
For what is worth I am also not getting any code actions in Neovim on version 4.5.1.

**Comment by skovhus** [comment]
I finally found time to spin up helix and debug what was going on. A fix has been released as version [4.6.1](https://github.com/bash-lsp/bash-language-server/pull/700/commits/3d9759f63a4da27328783048c0995599c429c975).

Let me know if it works for you. :) 

And feel free to add suggestions for future improvements of the language server.

**Comment by gegoune** [comment]
@skovhus Thanks for your work on bashls!

I am still not seeing all code actions that null-ls gives:
![bashls](https://user-images.githubusercontent.com/69750637/215062487-b0295ed6-95f4-482d-8ed2-0d5fc31c253f.png)

Actions for adding comment to disable checks are not given by bashls.
